services:
  postgres:
    image: postgres:latest
    container_name: PostgreSQL
    environment:
      - POSTGRES_USER=user_postgres
      - POSTGRES_PASSWORD=password_postgres
      - POSTGRES_DB=db0
    ports:
      - "10432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-config/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
